force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account1__c.field-meta.xml
<CustomField>
    <fullName>Account1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Actual_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Time__c</fullName>
    <label>Actual Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/EId__c.field-meta.xml
<CustomField>
    <fullName>EId__c</fullName>
    <externalId>true</externalId>
    <label>EId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Planned_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Time__c</fullName>
    <label>Planned Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>PostPone</fullName>
                <isActive>false</isActive>
                <label>PostPone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalenderManagerTest.cls
@isTest
public class CalenderManagerTest {

    public static testMethod void calenderTestMethod(){
        
        Account acc=new Account();
        acc.Name='testaccount';
        acc.Phone = '9985522322';
        acc.Contact_Person__c = 'test';
        acc.EId__c = 'S25321252hsb2';
      	acc.OwnerId = UserInfo.getUserId();
        acc.GeoLocation__latitude__s=23.733732;
        acc.GeoLocation__Longitude__s=69.859741;
        insert acc;
      	acc.Approval_Status__c = 'Approved';
         update acc;
        
         Visit__c vst2 = new Visit__c();
        vst2.Actual_Start_Time__c = system.now();
        vst2.Account1__c=acc.id;
        vst2.Planned_Start_Time__c = system.now();
        vst2.Status__c = 'Planned';
        vst2.OwnerId = UserInfo.getUserId();
        vst2.Comments__c = 'Reachndhd';
    	insert vst2;

        
        
        
        CalenderManager.accountData accdata = new CalenderManager.accountData();
         CalenderManager.calEvent call = new  CalenderManager.calEvent();
        call.startString = string.valueOf(system.now());
        call.endString = string.valueOf(system.now());
        call.dealerId = acc.id;
        call.ownerId = UserInfo.getUserId();
        call.id= vst2.id;
        CalenderManager.saveVisit(call);
        CalenderManager.listRecords(UserInfo.getUserId(),'test');
        CalenderManager.getRepresentative();
        CalenderManager.showEvents(UserInfo.getUserId(),string.valueOf(system.now()) ,string.valueOf(system.now()));
        CalenderManager.updateVisit(call);
        CalenderManager.deleteEvent(vst2.id);
        
        
    }
    
}