force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Planned_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Time__c</fullName>
    <label>Planned Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>PostPone</fullName>
                <isActive>false</isActive>
                <label>PostPone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/visitScheduler.cls
global class visitScheduler implements Database.Batchable <sObject>,Database.Stateful,Schedulable{
     
    global visitScheduler(){
    }
  
 global Database.QueryLocator start(Database.BatchableContext info){ 
	string pla = 'Planned';
     string inp = 'In Progress';
     String SOQL='SELECT Id,Planned_Start_Time__c,Status__c FROM visit__c where  Planned_Start_Time__c = TODAY and (Status__c=:pla OR Status__c=:inp)';
       return Database.getQueryLocator(SOQL);
   }     
   global void execute(Database.BatchableContext info, List<visit__c> scope){
       List<visit__c> visitsToUpdate = new List<visit__c>();
       for(visit__c a : scope)
          { 
           a.status__c = 'Incomplete';
           visitsToUpdate.add(a); 
       }       
       Database.SaveResult[] srList = Database.update(visitsToUpdate, false);
   
   }     
   global void finish(Database.BatchableContext info){ 
   
   } 
 
    global void execute(SchedulableContext SC){
        database.executeBatch(new visitScheduler(),100);
      
    } 
}