force-app/main/default/objects/Prospect__c/Prospect__c.object-meta.xml
<CustomObject>
    <label>Prospect</label>
    <nameField>
        <label>Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed lost</fullName>
            </value>
            <value>
                <fullName>Closed won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProspectTriggerTest.cls
@isTest
public class ProspectTriggerTest {

    public static testmethod void  testprospect(){
        Prospect__c prs = new Prospect__c();
        prs.Name = 'test';
        insert prs;
        prs.Status__c = 'Closed won';
        
        try{
            update prs;
        }catch(Exception e){
              
            system.debug(e.getMessage());
            System.assert(e.getMessage().contains('Please click on convert button to convert prospect'));
        }
    }
}