force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{0000}</displayFormat>
        <label>Invoice Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <label>Grand Total</label>
    <summarizedField>Invoice_item__c.Total_Price2__c</summarizedField>
    <summaryForeignKey>Invoice_item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <formula>TEXT(Order__r.Order_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order2__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_item__c/Invoice_item__c.object-meta.xml
<CustomObject>
    <label>Invoice item</label>
    <nameField>
        <displayFormat>IIT-{000000}</displayFormat>
        <label>Invoice item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>Invoice_line_items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Invoice_line_items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_item__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>Product__r.Product_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_item__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice items</relationshipLabel>
    <relationshipName>Invoice_items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_item__c/fields/TAX_Per_GST__c.field-meta.xml
<CustomField>
    <fullName>TAX_Per_GST__c</fullName>
    <label>TAX Per GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_item__c/fields/Tax_value__c.field-meta.xml
<CustomField>
    <fullName>Tax_value__c</fullName>
    <formula>( Unit_Price__c  *  Quantity__c ) *  TAX_Per_GST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_item__c/fields/Total_Price2__c.field-meta.xml
<CustomField>
    <fullName>Total_Price2__c</fullName>
    <formula>(Quantity__c *  Unit_Price__c) +  Tax_value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order2__c/Order2__c.object-meta.xml
<CustomObject>
    <label>Order2</label>
    <nameField>
        <displayFormat>ORD-{00000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order2__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Placed</fullName>
                <default>true</default>
                <label>Order Placed</label>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Packing</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order2__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order2__c/fields/Store_name__c.field-meta.xml
<CustomField>
    <fullName>Store_name__c</fullName>
    <formula>Store__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Store name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{00000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <label>Grand Total</label>
    <summarizedField>Order_Item__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Grand_Total_Edit__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total_Edit__c</fullName>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Store_name__c.field-meta.xml
<CustomField>
    <fullName>Store_name__c</fullName>
    <formula>Store__r.Name</formula>
    <label>Store name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Store_Name_Text__c.field-meta.xml
<CustomField>
    <fullName>Store_Name_Text__c</fullName>
    <label>Store Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{00000}</displayFormat>
        <label>Order Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Last_order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Last_order_Quantity__c</fullName>
    <label>Last order Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Price_MRP__c.field-meta.xml
<CustomField>
    <fullName>Price_MRP__c</fullName>
    <formula>Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/TAX_Per_GST__c.field-meta.xml
<CustomField>
    <fullName>TAX_Per_GST__c</fullName>
    <label>TAX Per GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Tax_Value__c.field-meta.xml
<CustomField>
    <fullName>Tax_Value__c</fullName>
    <formula>(Unit_Price__c * Quantity__c )* TAX_Per_GST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Tax_value_edit__c.field-meta.xml
<CustomField>
    <fullName>Tax_value_edit__c</fullName>
    <label>Tax value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Total_Edit__c.field-meta.xml
<CustomField>
    <fullName>Total_Edit__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>(Quantity__c * Unit_Price__c ) + Tax_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/TAX_Per_GST__c.field-meta.xml
<CustomField>
    <fullName>TAX_Per_GST__c</fullName>
    <label>TAX Per(GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/EId__c.field-meta.xml
<CustomField>
    <fullName>EId__c</fullName>
    <externalId>true</externalId>
    <label>EId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MasterDetail.cls
public class MasterDetail{
 
 @AuraEnabled(cacheable=true)
 public static List<pickValue> getPickValues(String objectName,string fieldName){
 
         Map<String, String> mapPickListValues = new Map<String, String>();
         Schema.SObjectType objSobjectType = Schema.getGlobalDescribe().get(objectName);
         Schema.DescribeSObjectResult objDescribeSobject = objSobjectType.getDescribe();
         Map<String, Schema.SObjectField> mapFields = objDescribeSobject.fields.getMap();
         List<Schema.PicklistEntry> lstPickListValues = mapFields.get(fieldName).getDescribe().getPickListValues();
         List<pickValue> pickValues =  new  List<pickValue>();
         for (Schema.PicklistEntry objPickList : lstPickListValues) {
             pickValue p = new pickValue();
             p.label =    objPickList.getLabel() ;
             p.value =    objPickList.getValue() ;
             pickValues.add(p);
         }
     system.debug(pickValues);
         return pickValues;
 
 
 }
 class pickValue{ 
 
   @AuraEnabled public string label{get;set;}
   @AuraEnabled  public string value{get;set;}
 }
    
    @AuraEnabled(cacheable=true)
    public static List<sobject> searchRecords(string  objectName, String fields, string filter ){ 
     
        
        string query = ' select ' + fields + ' from '+ objectName + filter;
        system.debug(query);
        return database.query(query);
        
    }
    @AuraEnabled(cacheable=true)
    public static records  readRecords(Id recordId){ 
        records records = new records(); 
        if(  recordId.getSObjectType().getDescribe().getName()  ==  'Order__c' ){
          records.orders = [ SELECT Visit__c, Store_name__c, Store__c,Store__r.Id,Store__r.Name, Store_Name_Text__c, OwnerId,  Order_Status__c, Order_Date__c, Name,  Id, Grand_Total__c, Grand_Total_Edit__c, EID__c FROM Order__c where id=: recordId  ] ;           
          records.order_items  = [ SELECT Id,  Name,Product__r.Name, Order__c, Current_Stock__c, Last_order_Quantity__c, Minimum_Stock__c, Price_MRP__c, Product_Name__c, Product__c, Quantity__c, TAX_Per_GST__c, Tax_Value__c, Total_Amount__c, Total_Price__c, Unit_Price__c, EID__c, Total_Edit__c, Tax_value_edit__c, Visit__c, Store__c FROM Order_Item__c   where Order__c=: recordId  ] ;           
        }
        if(  recordId.getSObjectType().getDescribe().getName()  ==  'Invoice__c' ){
          records.invoices = [ SELECT   Store__c,Store__r.Name,Store__r.Id,  OwnerId,  Invoice_Status__c, Invoice_Date__c, Name,  Id, Grand_Total__c,  EID__c FROM Invoice__c where id=: recordId  ] ;           
          records.invoice_items  = [  SELECT Id,   Name,   Invoice__c, Quantity__c, TAX_Per_GST__c, Unit_Price__c, Tax_value__c, Total_Price2__c, EID__c, Store__c FROM Invoice_item__c  where Invoice__c=: recordId  ] ;           
        }
        return records;     
        
    }
    @AuraEnabled(cacheable=false)
    public static records  saveRecords(string  recordsString ){  
        system.debug(recordsString);
         records records = (records)JSON.deserialize(recordsString, records.class);
         List<account>  accounts  = (  List<account>) records.accounts;
         List<order__c>  orders   = (  List<order__c>) records.orders;
         List<order_item__c>  order_items = (  List<order_item__c>) records.order_items;
         List<invoice__c>  invoices   = (  List<invoice__c>) records.invoices;
         List<invoice_item__c>  invoice_items = (  List<invoice_item__c>) records.invoice_items;        
        
         List<visit__c>  visits  = (  List<visit__c>) records.visits;
         List<product__c>  products  = (  List<product__c>) records.products;
         List<sobject> solist = new      List<sobject>();
        system.debug(records.invoices);
        system.debug(invoices);
         if( accounts != null){
              for(account  o :  accounts){
                   solist.add(o);
              }
         }
         if( visits != null){
             for(visit__c  o :  visits){
                  solist.add(o);
             }
         }
         if( orders != null){
             for(order__c  o :  orders){
                  solist.add(o);
             }
         }
         if( order_items != null){
             for(order_item__c o:  order_items){
                  o.order__r = new order__c(EID__c=o.EID__c.split('-')[0] );  
                  solist.add(o); 
             }
         } 
         if( invoices != null){
             for(sobject  i :  invoices){
                 system.debug(i);
                  solist.add(i);
             }
         }
         if( invoice_items != null){ 
             for(invoice_item__c i:  invoice_items){
                  i.Invoice__r = new Invoice__c(EID__c=i.EID__c.split('-')[0] );  
                  solist.add(i);  
             }
         } 
         upsert invoices;
         upsert solist; 
         return records;
    }
    
    public class records{
        @AuraEnabled public  List<account>  accounts ;
        @AuraEnabled public  List<order__c>  orders ;
        @AuraEnabled public  List<order_item__c>  order_items ;  
        @AuraEnabled public  List<invoice__c>  invoices ;
        @AuraEnabled public  List<invoice_item__c>  invoice_items ; 
        @AuraEnabled public  List<visit__c>  visits ;
        @AuraEnabled public  List<product__c>  products ;
    }
     
}