force-app/main/default/objects/Beat__c/Beat__c.object-meta.xml
<CustomObject>
    <label>Auto Beat</label>
    <nameField>
        <displayFormat>BEAT-{00}</displayFormat>
        <label>BEATID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auto Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat__c/fields/Executive__c.field-meta.xml
<CustomField>
    <fullName>Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Beats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat__c/fields/From_Day__c.field-meta.xml
<CustomField>
    <fullName>From_Day__c</fullName>
    <label>From Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Beat__c/fields/Next_Day_Order__c.field-meta.xml
<CustomField>
    <fullName>Next_Day_Order__c</fullName>
    <defaultValue>&apos;Day 1&apos;</defaultValue>
    <label>Next Day Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day 1</fullName>
            </value>
            <value>
                <fullName>Day 2</fullName>
            </value>
            <value>
                <fullName>Day 3</fullName>
            </value>
            <value>
                <fullName>Day 4</fullName>
            </value>
            <value>
                <fullName>Day 5</fullName>
            </value>
            <value>
                <fullName>Day 6</fullName>
            </value>
            <value>
                <fullName>Day 7</fullName>
            </value>
            <value>
                <fullName>Day 8</fullName>
            </value>
            <value>
                <fullName>Day 9</fullName>
            </value>
            <value>
                <fullName>Day 10</fullName>
            </value>
            <value>
                <fullName>Day 11</fullName>
            </value>
            <value>
                <fullName>Day 12</fullName>
            </value>
            <value>
                <fullName>Day 13</fullName>
            </value>
            <value>
                <fullName>Day 14</fullName>
            </value>
            <value>
                <fullName>Day 15</fullName>
            </value>
            <value>
                <fullName>Day 16</fullName>
            </value>
            <value>
                <fullName>Day 17</fullName>
            </value>
            <value>
                <fullName>Day 18</fullName>
            </value>
            <value>
                <fullName>Day 20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beat__c/fields/Number_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_Days__c</fullName>
    <label>Frequency of Visits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Beat__c/fields/Off_Days__c.field-meta.xml
<CustomField>
    <fullName>Off_Days__c</fullName>
    <label>Off Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursdays</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beat__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat__c/fields/To_Day__c.field-meta.xml
<CustomField>
    <fullName>To_Day__c</fullName>
    <label>To Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/Beat_Line__c.object-meta.xml
<CustomObject>
    <label>Beat Line</label>
    <nameField>
        <displayFormat>BTLN-{00}</displayFormat>
        <label>BTLN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat_Line__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beat Lines</relationshipLabel>
    <relationshipName>Beat_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Accounts__c.field-meta.xml
<CustomField>
    <fullName>Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store/Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beat Lines (Accounts)</relationshipLabel>
    <relationshipName>Beat_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Assigned_Beat_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Beat_User__c</fullName>
    <formula>Beat__r.User__r.FirstName &amp; &apos; &apos;  &amp; Beat__r.User__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned - Beat User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <label>Beat</label>
    <referenceTo>Beat__c</referenceTo>
    <relationshipLabel>Beat Lines</relationshipLabel>
    <relationshipName>Beat_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Beat_User__c.field-meta.xml
<CustomField>
    <fullName>Beat_User__c</fullName>
    <formula>Beat__r.User__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Beat User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Day_Order__c.field-meta.xml
<CustomField>
    <fullName>Day_Order__c</fullName>
    <label>Day Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day 1</fullName>
            </value>
            <value>
                <fullName>Day 2</fullName>
            </value>
            <value>
                <fullName>Day 3</fullName>
            </value>
            <value>
                <fullName>Day 4</fullName>
            </value>
            <value>
                <fullName>Day 5</fullName>
            </value>
            <value>
                <fullName>Day 6</fullName>
            </value>
            <value>
                <fullName>Day 7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Road</fullName>
            </value>
            <value>
                <fullName>Train</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Number_of_Visits_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Visits_Required__c</fullName>
    <formula>2 - Accounts__r.Number_of_Meetings__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Visits Required</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Sub_Mode_of_transport__c.field-meta.xml
<CustomField>
    <fullName>Sub_Mode_of_transport__c</fullName>
    <label>Sub Mode of transport</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mode_of_Transport__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2 wheeler</fullName>
            </value>
            <value>
                <fullName>4 wheeler</fullName>
            </value>
            <value>
                <fullName>Public Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Today_Selection__c.field-meta.xml
<CustomField>
    <fullName>Today_Selection__c</fullName>
    <formula>TEXT(Day_Order__c )  ==  TEXT(Beat__r.Next_Day_Order__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Today Selection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Type_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Visit__c</fullName>
    <label>Type of Visit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Customer Support</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Value Added Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/When__c.field-meta.xml
<CustomField>
    <fullName>When__c</fullName>
    <label>When?</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Where__c.field-meta.xml
<CustomField>
    <fullName>Where__c</fullName>
    <label>Where</label>
    <scale>6</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/With__c.field-meta.xml
<CustomField>
    <fullName>With__c</fullName>
    <label>With</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
                <default>true</default>
                <label>Self</label>
            </value>
            <value>
                <fullName>Teammate</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
                <isActive>false</isActive>
                <label>Manager</label>
            </value>
            <value>
                <fullName>Team Lead</fullName>
                <isActive>false</isActive>
                <label>Team Lead</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/With_Executive_2__c.field-meta.xml
<CustomField>
    <fullName>With_Executive_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>With Executive #2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Beat_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat_Skip__c/Beat_Skip__c.object-meta.xml
<CustomObject>
    <label>Beat Skip</label>
    <nameField>
        <label>Beat Skip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beat Skips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat_Skip__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat</label>
    <referenceTo>Beat__c</referenceTo>
    <relationshipLabel>Beat Skips</relationshipLabel>
    <relationshipName>Beat_Skips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Beat_Line__c.field-meta.xml
<CustomField>
    <fullName>Beat_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat Line</label>
    <referenceTo>Beat_Line__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BeatPlanner.cls
global class BeatPlanner {   
    
    @AuraEnabled
    public static List<Route__c> getRouteList(String uId) {
        return  [SELECT Id,Geolocation__Latitude__s , Geolocation__Longitude__s, Name FROM Route__c where ownerId =: uId]; 
        
    }
  public static string accountList {get;set;} 
  public static Route__c route  {get;set;} 
 
   public static pagereference getAccountsList( ) { 
   
   
       string beatId = ApexPages.currentPage().getParameters().get('id');
       string uId = ApexPages.currentPage().getParameters().get('eid');
       string routeId  = ApexPages.currentPage().getParameters().get('rid'); 
        if(routeId != null && routeId != ''){
          route =  [select id,Geolocation__Latitude__s , Geolocation__Longitude__s from Route__c where id=:routeId  ];
        }else{
            route =  [select id,Geolocation__Latitude__s , Geolocation__Longitude__s from Route__c  ][0];

        }

        List<Beat_Line__c> blist = [select id,Account__c from Beat_Line__c where beat__c =: beatId];  
        List<id> existds = new list<id>();
        for(Beat_Line__c b: blist){ 
           existds.add( b.Account__c); 
        }  
        
        
        accountList = JSON.serialize( [SELECT Id, Name,Owner.Name,Specialization__c, Geolocation__Latitude__s , Geolocation__Longitude__s FROM Account WHERE OwnerId=:uId AND Routes__c=:routeId and id not in : existds ]);
        return null; 
        
    }
   
    
    @AuraEnabled @remoteaction
    public static List<Account> getAccountList( string uId,string routeId , string beatId) { 
        
        route =  [select id,Geolocation__Latitude__s , Geolocation__Longitude__s from Route__c where id=:routeId  ];
        List<Beat_Line__c> blist = [select id,Account__c from Beat_Line__c where beat__c =: beatId]; 
        List<id> existds = new list<id>();
        for(Beat_Line__c b: blist){ 
           existds.add( b.Account__c);
        }  
        
        return [SELECT Id, Name,Owner.Name, Geolocation__Latitude__s ,Specialization__c, Geolocation__Longitude__s FROM Account WHERE OwnerId=:uId AND Routes__c=:routeId and id not in : existds ]; 
        
    }
    
    

    
    public static  Map<decimal, List<Beat_Line__c>> bmap  {get;set;}
    @AuraEnabled
    public static void getbeatLineList() {
        string   beatId = apexpages.currentPage().getParameters().get('id'); 
        bmap  =  new  Map<decimal, List<Beat_Line__c>>();
        Beat__c beat = [select id, Number_Days__c from beat__c where id=: beatId];
        List<Beat_Line__c>  blist = [ SELECT Id, day__c, Name,  Beat__c, Account__c,  Account__r.Name FROM Beat_Line__c where beat__c=:BeatId order by Day__c asc ];
        for(Beat_Line__c b: blist){ 
            if(bmap.containsKey(b.day__c)) 
            {
                bmap.get(b.day__c).add(b);
            }else{
                bmap.put(b.day__c, new list<Beat_Line__c>{b} );
            }
        } 
        for(decimal i=1;i<=beat.Number_Days__c;i++){
            
            if(bmap.get(i) ==null){
                bmap.put(i, new List<Beat_Line__c>()) ;
                system.debug(i);
            }
            
           
        }
        system.debug( 'bmap'+bmap);
    }
   
    
    @AuraEnabled
    public static void createBeatLines( string uId, string  beatId,string day,List<sobject> lines) {
        List<Beat_Line__c> bList = new List<Beat_Line__c>();
       //SELECT Id, Day__c, Today_Selection__c, Sub_Mode_of_transport__c, Number_of_Visits_Required__c,
       // Beat_User__c, Assigned_Beat_User__c, With__c, With_Executive_2__c, Where__Longitude__s, 
       // Where__Latitude__s, When__c, Type_of_Visit__c, Mode_of_Transport__c, Day_Order__c, Accounts__c,
       //  Account__c, Beat__c, Name FROM Beat_Line__c
       //  
    
        for(sobject so: lines){
            
            Account  a = (Account )so;
            Beat_Line__c bl= new Beat_Line__c();
            bl.Beat__c = beatId;
            bl.Day__c = integer.valueof( day );
            bl.Account__c = a.id;
            bList.add(bl); 
            
            
        }
        insert bList;
         
        
     }
    @remoteaction
    public static string deleteVisitPlan(String deleteId){
        delete [select id from beat_line__c where id=: deleteId];  
        return 'success';
        
    }
     @AuraEnabled
    public static void createVisits(  string beatId) { 
        Beat__c beat = [SELECT Id, Name, Next_Day_Order__c, To_Day__c, Executive__c, From_Day__c, Number_Days__c, Off_Days__c FROM Beat__c where id=:beatId ];
        List<Beat_Line__c>  blist = [ SELECT Id, day__c, Name,  Beat__c, Account__c,  Account__r.Name, Day_Order__c, Mode_of_Transport__c, Type_of_Visit__c, When__c, Where__Latitude__s, Where__Longitude__s, Where__c,         Sub_Mode_of_transport__c FROM Beat_Line__c where beat__c=:BeatId order by Day__c asc ];
        List<visit__c> visitExList = [select id,status__c from visit__c where Beat_Line__c in:blist and status__c = 'Planned' ];
       List<Holiday__c> hlist = [select id,date__c from Holiday__c];
        List<Beat_Skip__c> bslist = [select id,Date_Skipped__c from Beat_Skip__c]; 
        
         delete visitExList;
        
         Set<Id> beatLines = new  Set<Id>();
         Set<date> skipset = new  Set<date>();
         List<visit__c> vlist = new  List<visit__c>(); 

         for(Holiday__c h: hlist){
            skipset.add(h.date__c);
         } 
         for(Beat_Skip__c b: bslist){
             skipset.add(b.Date_Skipped__c);
         }  
        
        datetime startdate = beat.From_Day__c;
        datetime enddate = beat.To_Day__c;
        datetime currDate =  startdate;
        decimal oldday = 1;
        while(currDate <= enddate){
              
              for(Beat_Line__c bl : blist){ 
                 visit__c v = new visit__c();
                 
                  if(oldday !=  bl.Day__c){
                      oldday =  bl.Day__c;
                      currDate = currDate.addDays( 1 );
                  }
                   
               
                  while((beat.Off_Days__c != null && beat.Off_Days__c.contains(currDate.format('EEEE') )) ||   skipset.contains( date.valueof( currDate ) )  ){
                      currDate = currDate.addDays(1);
                  } 
                  
                  v.Planned_Start_Time__c = currDate;
                  v.Status__c = 'Planned';  
                  v.Account1__c = bl.Account__c;
                  v.Beat_Line__c = bl.id;
                  currDate = v.Planned_Start_Time__c;
                  v.ownerId = beat.Executive__c;
                  vlist.add(v); 
                  
            }
 
         }
       
        insert vlist;
    
    }
 
}