force-app/main/default/objects/New_Beat__c/New_Beat__c.object-meta.xml
<CustomObject>
    <label>Run Beat</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>BeatId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Run Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Beat__c/fields/Beat_Date__c.field-meta.xml
<CustomField>
    <fullName>Beat_Date__c</fullName>
    <label>Beat Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/New_Beat__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <label>Route</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Beat__c/fields/Routes__c.field-meta.xml
<CustomField>
    <fullName>Routes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>New_Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/New_Beat__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipName>New_Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Center</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account1__c.field-meta.xml
<CustomField>
    <fullName>Account1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Actual_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Time__c</fullName>
    <label>Actual Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/EId__c.field-meta.xml
<CustomField>
    <fullName>EId__c</fullName>
    <externalId>true</externalId>
    <label>EId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Visit__c/fields/New_Beat__c.field-meta.xml
<CustomField>
    <fullName>New_Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat</label>
    <referenceTo>New_Beat__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Planned_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Time__c</fullName>
    <label>Planned Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>PostPone</fullName>
                <isActive>false</isActive>
                <label>PostPone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/newBeatControllerTest.cls
@isTest
public class newBeatControllerTest {
    Public static testmethod void testnewbeat(){
        
        Warehouse__c wh = new Warehouse__c();
        wh.name = 'test';
        insert wh;
        Route__c rut = new Route__c();
        rut.warehouse__c = wh.id;
        rut.Name = 'test route';
        insert rut;
       List<Account> acLIst = new List<Account>();
        Account acc=new Account();
        acc.Name='testaccount';
        acc.Phone = '9985522322';
        acc.Contact_Person__c = 'test';
        acc.EId__c = 'S25321252hsb2';
      	acc.OwnerId = UserInfo.getUserId();
        acc.GeoLocation__latitude__s=23.733732;
        acc.GeoLocation__Longitude__s=69.859741;
        acc.warehouse__c = rut.warehouse__c;
        acc.routes__c = rut.id;
        acLIst.add(acc);
        insert acLIst;
      	acLIst[0].Approval_Status__c = 'Approved';
         update acLIst;
        
        New_Beat__c nbn = new New_Beat__c();
        nbn.warehouse__c = rut.warehouse__c;
        nbn.routes__c = rut.id;
        nbn.Beat_Date__c = system.today();
        insert nbn;
        List<visit__c> vList = new List<visit__c>();
         Visit__c vst = new Visit__c();
        vst.Actual_Start_Time__c = system.now();
        vst.Account1__c=acLIst[0].id;
        vst.Planned_Start_Time__c = system.now();
        vst.Status__c = 'Planned';
        vst.Comments__c = 'Reachndhd';
        vst.New_Beat__c = nbn.id;
       vList.add(vst);
        insert vList;
        
        Visit__c vst2 = new Visit__c();
        vst2.Actual_Start_Time__c = system.now();
        vst2.Account1__c=acLIst[0].id;
        vst2.Planned_Start_Time__c = system.now();
        vst2.Status__c = 'Planned';
        vst2.Comments__c = 'Reachndhd';
    	
        
        
       Test.startTest();
            newBeatController.getUserList();
        newBeatController.getRouteList(userinfo.getUserId());
        newBeatController.getStoreList(userinfo.getUserId(),rut.id);
        newBeatController.getbeatList(userinfo.getUserId(),rut.id);
        newBeatController.getvisitList(nbn.id);
        newBeatController.createBeat(userinfo.getUserId(),acLIst,system.today(),rut.id);
        newBeatController.createnewBeat(userinfo.getUserId(),vList,system.today(),rut.id);
        newBeatController.getupcominbeats(userinfo.getUserId());
        newBeatController.changeVisitOwner(userinfo.getUserId(),vList,userinfo.getUserId(),nbn.id);
        Test.stopTest();   
            
            
        
    }
}