force-app/main/default/objects/New_Beat__c/New_Beat__c.object-meta.xml
<CustomObject>
    <label>Run Beat</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>BeatId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Run Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Beat__c/fields/Beat_Date__c.field-meta.xml
<CustomField>
    <fullName>Beat_Date__c</fullName>
    <label>Beat Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/New_Beat__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <label>Route</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Beat__c/fields/RouteName__c.field-meta.xml
<CustomField>
    <fullName>RouteName__c</fullName>
    <formula>Routes__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RouteName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Beat__c/fields/Routes__c.field-meta.xml
<CustomField>
    <fullName>Routes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>New_Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/New_Beat__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipName>New_Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/New_Beat__c/fields/WarehouseName__c.field-meta.xml
<CustomField>
    <fullName>WarehouseName__c</fullName>
    <formula>Warehouse__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WarehouseName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Center</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahmednagar</fullName>
            </value>
            <value>
                <fullName>Akola</fullName>
            </value>
            <value>
                <fullName>Amravati</fullName>
            </value>
            <value>
                <fullName>Beed</fullName>
            </value>
            <value>
                <fullName>Bhandara</fullName>
            </value>
            <value>
                <fullName>Buldhana</fullName>
            </value>
            <value>
                <fullName>Chandrapur</fullName>
            </value>
            <value>
                <fullName>Osmanabad</fullName>
            </value>
            <value>
                <fullName>Dhule</fullName>
            </value>
            <value>
                <fullName>Gadchiroli</fullName>
            </value>
            <value>
                <fullName>Gondia</fullName>
            </value>
            <value>
                <fullName>Hingoli</fullName>
            </value>
            <value>
                <fullName>Jalgaon</fullName>
            </value>
            <value>
                <fullName>Jalna</fullName>
            </value>
            <value>
                <fullName>Kolhapur</fullName>
            </value>
            <value>
                <fullName>Latur</fullName>
            </value>
            <value>
                <fullName>Mumbai City</fullName>
            </value>
            <value>
                <fullName>Mumbai Suburban</fullName>
            </value>
            <value>
                <fullName>Nanded</fullName>
            </value>
            <value>
                <fullName>Nandurbar</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Nashik</fullName>
            </value>
            <value>
                <fullName>Palghar</fullName>
            </value>
            <value>
                <fullName>Parbhani</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Raigad</fullName>
            </value>
            <value>
                <fullName>Ratnagiri</fullName>
            </value>
            <value>
                <fullName>Aurangabad</fullName>
            </value>
            <value>
                <fullName>Sangli</fullName>
            </value>
            <value>
                <fullName>Satara</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account1__c.field-meta.xml
<CustomField>
    <fullName>Account1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/New_Beat__c.field-meta.xml
<CustomField>
    <fullName>New_Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat</label>
    <referenceTo>New_Beat__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Planned_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Time__c</fullName>
    <label>Planned Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>PostPone</fullName>
                <isActive>false</isActive>
                <label>PostPone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/newBeatController.cls
public class newBeatController {
  @AuraEnabled
    public static List<user> getUserList() {
        user u = [SELECT Id,Name,Profile.Name FROM User WHERE Id=:userinfo.getUserId() LIMIT 1];
        if(u.Profile.Name == 'Sales executive'){
            return [SELECT Id,Name,Routes__c FROM user WHERE Id=:userinfo.getUserId() ORDER BY Name ASC];
        }else{
            return [SELECT Id,Name,Routes__c FROM user ORDER BY Name ASC];
        }
        
        
    }
      @AuraEnabled
    public static List<Route__c> getRouteList(string uId) {
        return [SELECT Id,Name FROM Route__c WHERE ownerId =:uId ];
    }
    @AuraEnabled
    public static List<Account> getStoreList( string uId,string route) {
       
        return [SELECT id,Name,RouteName__c,WarehouseName__c,Owner.Name,State__c,Store_Category__c,District__c,Grade__c FROM Account WHERE ownerId=:uId AND Routes__c=:route AND Approval_Status__c='Approved'];
        
    }
    @AuraEnabled
    public static List<New_Beat__c> getbeatList( string uId,string route) {
       
        return [SELECT id,Name,Route__c,Owner.Name,Beat_Date__c,RouteName__c,WarehouseName__c FROM New_Beat__c WHERE ownerId=:uId AND Routes__c=:route ORDER BY  Beat_Date__c DESC NULLS LAST];
        
    }
     @AuraEnabled
    public static List<visit__c> getvisitList( string BeatId) {
       
        return [SELECT id,Name,Account1__c,Account_Name__c,Status__c,Planned_start_time__c,Account1__r.Routes__c FROM visit__c WHERE New_Beat__c=:BeatId ];
        
}
	 @AuraEnabled
    public static List<New_Beat__c> createBeat( string uId,List<Account> stores,date sdate,string route) {
        //system.debug('1');
        List<visit__c> vList = new List<visit__c>();
        route__c rt = [SELECT id,Name,warehouse__c FROM route__c WHERE id =:route];
        New_Beat__c nb = new New_Beat__c();
        nb.Beat_Date__c = sdate;
        nb.Routes__c = route;
        nb.warehouse__c = rt.warehouse__c;
        nb.OwnerId = uId;
        insert nb;
        //system.debug('2');
        for(Account acc : stores){
            visit__c v = new visit__c();
            v.Account1__c = acc.id;
            v.New_Beat__c = nb.id;
            v.Planned_Start_Time__c = sdate;
            v.Status__c = 'Planned';
            v.OwnerId = uId;
            vList.add(v);
        }
         //system.debug('3');
        insert vList;
           //system.debug('4');
         return [SELECT id,Name,Route__c,Owner.Name,Beat_Date__c,RouteName__c,WarehouseName__c FROM New_Beat__c WHERE ownerId=:uId AND Routes__c=:route ORDER BY  Beat_Date__c DESC NULLS LAST];
    }
     @AuraEnabled
    public static List<New_Beat__c> createnewBeat( string uId,List<visit__c> stores,date sdate,string route) {
        List<visit__c> vList = new List<visit__c>();
        route__c rt = [SELECT id,Name,warehouse__c FROM route__c WHERE id =:route];
        New_Beat__c nb = new New_Beat__c();
        nb.Beat_Date__c = sdate;
        nb.Routes__c = route;
        nb.warehouse__c = rt.warehouse__c;
        nb.OwnerId = uId;
        insert nb;
        for(visit__c acc : stores){
            visit__c v = new visit__c();
            v.Account1__c = acc.Account1__c;
            v.New_Beat__c = nb.id;
            v.Planned_Start_Time__c = sdate; 
            v.Status__c = 'Planned';
            v.OwnerId = uId;
            vList.add(v);
        }
        insert vList;
         return [SELECT id,Name,Route__c,Owner.Name,Beat_Date__c,RouteName__c,WarehouseName__c FROM New_Beat__c WHERE ownerId=:uId AND Routes__c=:route ORDER BY  Beat_Date__c DESC NULLS LAST];
    }
     @AuraEnabled
    public static List<New_Beat__c> getupcominbeats( string uId) {
        return [SELECT id,Name,Route__c,Owner.Name,Beat_Date__c,RouteName__c,WarehouseName__c FROM New_Beat__c WHERE ownerId=:uId AND Beat_Date__c >= TODAY ORDER BY  Beat_Date__c DESC NULLS LAST];
        
    }
     @AuraEnabled
    public static List<New_Beat__c> changeVisitOwner( string uId,List<visit__c> stores,string assId,string beId) {
        List<visit__c> vList = new List<visit__c>();
       New_Beat__c nb = [SELECT id,name,OwnerId,Routes__c,warehouse__c,Beat_Date__c FROM New_Beat__c WHERE id=:beId LIMIT 1];
       
        New_Beat__c newnb = new New_Beat__c();
         newnb.OwnerId = assId;
        newnb.Beat_Date__c = nb.Beat_Date__c;
        newnb.warehouse__c = nb.warehouse__c;
        newnb.Route__c = nb.Routes__c;
        insert newnb;
        for(visit__c acc : stores){
            visit__c v = new visit__c(id=acc.id);
            v.New_Beat__c = newnb.id;
            v.OwnerId = assId;
            vList.add(v);
        }
        
        update vList;
         return [SELECT id,Name,Route__c,Owner.Name,Beat_Date__c,RouteName__c,WarehouseName__c FROM New_Beat__c WHERE ownerId=:uId AND Beat_Date__c >= TODAY ORDER BY  Beat_Date__c DESC NULLS LAST];
    }
}