force-app/main/default/objects/DailyLog__c/DailyLog__c.object-meta.xml
<CustomObject>
    <label>Daily logs</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyLog__c/fields/Clock_In__c.field-meta.xml
<CustomField>
    <fullName>Clock_In__c</fullName>
    <label>Day started time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DailyLog__c/fields/Clock_Out__c.field-meta.xml
<CustomField>
    <fullName>Clock_Out__c</fullName>
    <label>Day ended time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DailyLog__c/fields/First_Check_In_Visit__c.field-meta.xml
<CustomField>
    <fullName>First_Check_In_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Check-In Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyLog__c/fields/Last_Check_Out_Visit__c.field-meta.xml
<CustomField>
    <fullName>Last_Check_Out_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Check Out Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Logs (Last Check Out Visit)</relationshipLabel>
    <relationshipName>Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Actual_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Time__c</fullName>
    <label>Actual End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Actual_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Time__c</fullName>
    <label>Actual Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Clock_In__c.field-meta.xml
<CustomField>
    <fullName>Clock_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clock In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Clock_Out__c.field-meta.xml
<CustomField>
    <fullName>Clock_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clock Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Planned_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Time__c</fullName>
    <label>Planned Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/schedulerEndDay.cls
global class schedulerEndDay implements Database.Batchable <sObject>,Database.Stateful,Schedulable{
     
    global schedulerEndDay(){
    }
  
 global Database.QueryLocator start(Database.BatchableContext info){ 

     String SOQL='SELECT id,Clock_In__c,Clock_Out__c,First_Check_In_Visit__c,Last_Check_Out_Visit__c,OwnerId from  DailyLog__c  WHERE  Clock_In__c =TODAY';
       return Database.getQueryLocator(SOQL);
   }     
   global void execute(Database.BatchableContext info, List<DailyLog__c> scope){
       List<DailyLog__c> logsToUpdate = new List<DailyLog__c>();
       for(DailyLog__c a : scope)
          { 
              if(a.Clock_Out__c ==null){
                   a.Clock_Out__c = system.now();
                 
              }
              List<visit__c> vList = [Select id,Actual_Start_Time__c,Actual_End_Time__c from Visit__c WHERE Planned_Start_Time__c = TODAY AND ownerId=:a.OwnerId AND Actual_Start_Time__c != null Order by Actual_Start_Time__c ASC];
    if(vList.size() >0){
        a.First_Check_In_Visit__c = vList[0].id;
        
        if(vList[vList.size()-1].Actual_End_Time__c != null){
           a.Last_Check_Out_Visit__c = vList[vList.size()-1].id;
        }else{
            if(vList.size() >1){
                a.Last_Check_Out_Visit__c = vList[vList.size()-2].id;
            }
        }
        logsToUpdate.add(a); 
    }
          
       }       
       Database.SaveResult[] srList = Database.update(logsToUpdate, false);
   
   }     
   global void finish(Database.BatchableContext info){ 
   
       
   } 
 
    global void execute(SchedulableContext SC){
        database.executeBatch(new schedulerEndDay(),100);
      
    } 
}