force-app/main/default/objects/DailyLog__c/DailyLog__c.object-meta.xml
<CustomObject>
    <label>Daily logs</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyLog__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DailyLog__c/fields/Clock_In__c.field-meta.xml
<CustomField>
    <fullName>Clock_In__c</fullName>
    <label>Day started time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{00000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{00000}</displayFormat>
        <label>Order Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Center</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account1__c.field-meta.xml
<CustomField>
    <fullName>Account1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Actual_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Time__c</fullName>
    <label>Actual Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Clock_In__c.field-meta.xml
<CustomField>
    <fullName>Clock_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clock In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/EId__c.field-meta.xml
<CustomField>
    <fullName>EId__c</fullName>
    <externalId>true</externalId>
    <label>EId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Planned_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Time__c</fullName>
    <label>Planned Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>PostPone</fullName>
                <isActive>false</isActive>
                <label>PostPone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/visitManagerTest.cls
@isTest
public class visitManagerTest {
	 public static testMethod void movetoNext(){
         Warehouse__c wh = new Warehouse__c();
        wh.name = 'test';
        insert wh;
        List<Route__c> rut = new List<Route__c>();
        Route__c r = new Route__c();
        r.warehouse__c = wh.id;
        r.Name = 'test route';
        rut.add(r);
        insert rut;
          List<Account> acLIst = new List<Account>();
        Account acc=new Account();
        acc.Name='testaccount';
        acc.Phone = '9985522322';
        acc.Contact_Person__c = 'test';
        acc.Store_Category__c = 'Hyper market';
        acc.Grade__c = 'A';
        acc.EId__c = 'S25321252hsb2';
      	acc.OwnerId = UserInfo.getUserId();
        acc.GeoLocation__latitude__s=23.733732;
        acc.GeoLocation__Longitude__s=69.859741;
        acc.warehouse__c = rut[0].warehouse__c;
        acc.routes__c = rut[0].id;
        acc.Approval_Status__c = 'Approved';
         acLIst.add(acc);
        insert acLIst;
      	
         List<Visit__c> visitList = new List<Visit__c>();
        /*Visit__c vst1 = new Visit__c();
        vst1.Actual_Start_Time__c = System.now();
        vst1.Planned_Start_Time__c = System.now();
        vst1.Account1__c=acc.id;
         vst1.Eid__c = 'mnh25ad221a5';
        vst1.Status__c = 'Planned';
        vst1.Comments__c = 'Reach ASAP';
        visitList.add(vst1);*/
         
        
        Visit__c vst2 = new Visit__c();
        vst2.Actual_Start_Time__c = system.now();
        vst2.Account1__c=acLIst[0].id;
        vst2.Planned_Start_Time__c = system.now();
        vst2.Eid__c = 'mnh25ad221a5';
        vst2.Status__c = 'Planned';
        vst2.Comments__c = 'Reachndhd';
         visitList.add(vst2);
        insert visitList;
         
         Product__c pro = new Product__c();
         pro.Name = 'test';
         insert pro;
         
         string acid= acc.id;
         string pid = pro.id;
         Order__c ord = new Order__c();
         ord.Store__c = acLIst[0].id;
         insert ord;
         List<Order_Item__c> oiList = new List<Order_Item__c>();
         Order_Item__c oitem = new Order_Item__c();
         oitem.order__c= ord.Id;
         
         oiList.add(oitem);
string ord1 = JSON.serialize(oitem);
         DailyLog__c dl = new DailyLog__c();
         dl.Clock_In__c = system.now();
         dl.Clock_In_Location__Latitude__s = 23.733732;
         dl.Clock_In_Location__Longitude__s = 69.859741;
         insert dl;
         string vs1 = JSON.serialize(visitList);
        // VisitManager.getdata();
        // VisitManager.getUserRoutes();
        // VisitManager.getWarehouses();
         VisitManager.getAccounts();
         VisitManager.upsertAccounts(acLIst);
         VisitManager.getTodaysVisits();
         VisitManager.upsertVisits(vs1);
         VisitManager.getDailyLog();
         VisitManager.upsertDailyLog(dl);
         VisitManager.getproductList();
         VisitManager.getOrderItems();
         VisitManager.upsertOrderItem(ord1);
     }
    
}