force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Un qualified</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beat__c/Beat__c.object-meta.xml
<CustomObject>
    <label>Auto Beat</label>
    <nameField>
        <displayFormat>BEAT-{00}</displayFormat>
        <label>BEATID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auto Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat__c/fields/Executive__c.field-meta.xml
<CustomField>
    <fullName>Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Beats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat__c/fields/From_Day__c.field-meta.xml
<CustomField>
    <fullName>From_Day__c</fullName>
    <label>From Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Beat__c/fields/Number_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_Days__c</fullName>
    <label>Frequency of Visits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Beat__c/fields/Off_Days__c.field-meta.xml
<CustomField>
    <fullName>Off_Days__c</fullName>
    <label>Off Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursdays</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beat__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat__c/fields/To_Day__c.field-meta.xml
<CustomField>
    <fullName>To_Day__c</fullName>
    <label>To Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/Beat_Line__c.object-meta.xml
<CustomObject>
    <label>Beat Line</label>
    <nameField>
        <displayFormat>BTLN-{00}</displayFormat>
        <label>BTLN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat_Line__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beat Lines</relationshipLabel>
    <relationshipName>Beat_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <label>Beat</label>
    <referenceTo>Beat__c</referenceTo>
    <relationshipLabel>Beat Lines</relationshipLabel>
    <relationshipName>Beat_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Beat_Line__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Center</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahmednagar</fullName>
            </value>
            <value>
                <fullName>Akola</fullName>
            </value>
            <value>
                <fullName>Amravati</fullName>
            </value>
            <value>
                <fullName>Beed</fullName>
            </value>
            <value>
                <fullName>Bhandara</fullName>
            </value>
            <value>
                <fullName>Buldhana</fullName>
            </value>
            <value>
                <fullName>Chandrapur</fullName>
            </value>
            <value>
                <fullName>Osmanabad</fullName>
            </value>
            <value>
                <fullName>Dhule</fullName>
            </value>
            <value>
                <fullName>Gadchiroli</fullName>
            </value>
            <value>
                <fullName>Gondia</fullName>
            </value>
            <value>
                <fullName>Hingoli</fullName>
            </value>
            <value>
                <fullName>Jalgaon</fullName>
            </value>
            <value>
                <fullName>Jalna</fullName>
            </value>
            <value>
                <fullName>Kolhapur</fullName>
            </value>
            <value>
                <fullName>Latur</fullName>
            </value>
            <value>
                <fullName>Mumbai City</fullName>
            </value>
            <value>
                <fullName>Mumbai Suburban</fullName>
            </value>
            <value>
                <fullName>Nanded</fullName>
            </value>
            <value>
                <fullName>Nandurbar</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Nashik</fullName>
            </value>
            <value>
                <fullName>Palghar</fullName>
            </value>
            <value>
                <fullName>Parbhani</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Raigad</fullName>
            </value>
            <value>
                <fullName>Ratnagiri</fullName>
            </value>
            <value>
                <fullName>Aurangabad</fullName>
            </value>
            <value>
                <fullName>Sangli</fullName>
            </value>
            <value>
                <fullName>Satara</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account1__c.field-meta.xml
<CustomField>
    <fullName>Account1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Beat_Line__c.field-meta.xml
<CustomField>
    <fullName>Beat_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat Line</label>
    <referenceTo>Beat_Line__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Planned_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Time__c</fullName>
    <label>Planned Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>PostPone</fullName>
                <isActive>false</isActive>
                <label>PostPone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestBeatPlanner.cls
@isTest
public class TestBeatPlanner {
   @isTest public static void testBeat(){
        Id u=userinfo.getUserId();
        list<Visit__c>lstVist = new list<Visit__c>();
        list< Route__c>lstRoute =new list<Route__c>();
         beat__c bt = new beat__c();
        bt.Executive__c = userinfo.getUserId();
        bt.From_Day__c = date.today();
        bt.To_Day__c  = date.today().adddays(1);
        bt.Off_Days__c = 'Sunday';
        bt.Number_Days__c = 1;
        insert bt;
   
     
     
        Route__c rt =new Route__c (Name='TestMuncipality' );
        lstRoute.add(rt);
        Route__c rt1 =new Route__c (Name='TestMuncipality1' );
        lstRoute.add(rt1);
        insert lstRoute;
       
        
        List<account> lstacc = new List<account>();
       
        
        Account acc=new Account(Name='Test',Approval_Status__c='approved',phone='1111111111',State__c='Kerala',District__c='Kannur',Routes__c=rt.Id,ownerId=UserInfo.getUserId());
        insert acc;
        lstacc.add(acc);
        
        Account acc1=new Account(Name='Test122',Approval_Status__c='approved',phone='1111111111',State__c='Kerala',District__c='Kannur',Routes__c=rt.Id,ownerId=UserInfo.getUserId());
        insert acc1;
        
        lstacc.add(acc1);
     
     
        beat_line__c bl = new beat_line__c();
        bl.Day__c = 1;
        bl.Beat__c = bt.id;
        bl.account__c = acc.id; 
        insert bl;
        bl = new beat_line__c();
        bl.account__c = acc.id; 
        bl.Day__c = 2;
        bl.Beat__c = bt.id; 
        insert bl;
     
         Visit__c vst = new Visit__c();
         vst.Planned_Start_Time__c = system.now();
         vst.Status__c = 'Planned';
         vst.OwnerId =UserInfo.getUserId();
        vst.Account1__c = acc1.Id;
        lstVist.add(vst);
        Visit__c vst1 = new Visit__c();
        vst1.Planned_Start_Time__c = system.now();
        vst1.Account1__c =acc.Id;
        vst1.Status__c = 'Planned';
         vst1.OwnerId =UserInfo.getUserId();
        lstVist.add(vst1);
         Visit__c vst2 = new Visit__c();
        vst2.Planned_Start_Time__c = system.now();
        vst2.Account1__c =acc.Id;
        vst2.Status__c = 'Planned';
        vst2.OwnerId =UserInfo.getUserId();
        lstVist.add(vst2);
        insert lstVist;
        Test.startTest();
        
        Pagereference p =  page.beatplanner;
         p.getParameters().put('id',  bt.id);
      
       Test.setCurrentPage(p);//Applying page context here
 
       ApexPages.currentPage().getParameters().put('id', bt.id);
      
         beatplanner.createBeatLines(userinfo.getUserId(),bt.id, '1',lstacc ); 
         beatplanner.createVisits(bt.Id);
        
         Test.stopTest();   
        
    }
  @isTest public static void testBeat1(){
        Id u=userinfo.getUserId();
        
        list<Visit__c>lstVist = new list<Visit__c>();
        list< Route__c>lstRoute =new list<Route__c>();
        list<Account> lstacc = new list<Account>();
        beat__c bt = new beat__c();
        bt.Executive__c = userinfo.getUserId();
        bt.From_Day__c = date.today();
        bt.To_Day__c  = date.today().adddays(1);
        bt.Off_Days__c = 'Sunday';
        bt.Number_Days__c = 1;
        insert bt;
   
     
     
        Route__c rt =new Route__c (Name='TestMuncipality' );
        lstRoute.add(rt);
        Route__c rt1 =new Route__c (Name='TestMuncipality1' );
        lstRoute.add(rt1);
        insert lstRoute;
        
        
      
       
        
        Account acc=new Account(Name='Test',Approval_Status__c='approved',phone='1111111111',State__c='Kerala',District__c='Kannur',Routes__c=rt.Id,ownerId=UserInfo.getUserId());
        insert acc;
        lstacc.add(acc);
        
        Account acc1=new Account(Name='Test122',Approval_Status__c='approved',phone='1111111111',State__c='Kerala',District__c='Kannur',Routes__c=rt.Id,ownerId=UserInfo.getUserId());
        insert acc1;
        
        lstacc.add(acc1);
     
     
          beat_line__c bl = new beat_line__c();
        bl.account__c = acc.id;
        bl.Day__c = 1;
        bl.Beat__c = bt.id;
        insert bl;
     
         Visit__c vst = new Visit__c();
        vst.Planned_Start_Time__c = system.now();
         vst.Status__c = 'Planned';
         vst.OwnerId =UserInfo.getUserId();
        vst.Account1__c =acc.Id;
        lstVist.add(vst);
        Visit__c vst1 = new Visit__c();
        vst1.Planned_Start_Time__c = system.now();
        vst1.Account1__c =acc.Id;
        vst1.Status__c = 'Planned';
         vst1.OwnerId =UserInfo.getUserId();
        lstVist.add(vst1);
         Visit__c vst2 = new Visit__c();
        vst2.Planned_Start_Time__c = system.now();
        vst2.Account1__c =acc.Id;
        vst2.Status__c = 'Planned';
        vst2.OwnerId =UserInfo.getUserId();
        lstVist.add(vst2);
        insert lstVist;
        Test.startTest();
        
        Pagereference p =  page.beatplanner;
         p.getParameters().put('id',  bt.id);
      
       Test.setCurrentPage(p);//Applying page context here
 
        ApexPages.currentPage().getParameters().put('id', bt.id);
      
        beatplanner.getRouteList();
        beatplanner.getAccountList(UserInfo.getUserId(),rt.Id,bt.id);
        beatplanner.getbeatLineList();
 
         Test.stopTest();   
        
    }
}