force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EP-{00000}</displayFormat>
        <label>Expense Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/DA__c.field-meta.xml
<CustomField>
    <fullName>DA__c</fullName>
    <label>DA</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Comments__c.field-meta.xml
<CustomField>
    <fullName>Expense_Comments__c</fullName>
    <label>Expense Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Expense Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Other_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Other_Expenses__c</fullName>
    <label>Other Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/TA__c.field-meta.xml
<CustomField>
    <fullName>TA__c</fullName>
    <label>TA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/customNewExpenseControllerTest.cls
@isTest
public class customNewExpenseControllerTest {

    Public static testmethod void testexpense(){
        
        Expense__c exp = new Expense__c();
        exp.Expense_Date__c = system.today();
        exp.TA__c = 100;
        exp.DA__c = 100;
        exp.Other_Expenses__c = 100;
        exp.Expense_Comments__c = 'test';
        
        Test.startTest();
        customNewExpenseController.dataBox db = new customNewExpenseController.dataBox();
        customNewExpenseController.getDates();
        customNewExpenseController.insertExpense(exp);
        customNewExpenseController.submitapproval(exp.id);
        Test.stopTest();
    }
}