force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EP-{00000}</displayFormat>
        <label>Expense Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(Approval_Status_Formula__c, &apos;Approved&apos;, IMAGE(&quot;/resource/Approved&quot;, &quot;Rejected&quot;,140,140), &apos;Rejected&apos;, IMAGE(&quot;/resource/Rejected&quot;, &quot;Rejected&quot;,150,175),&apos;Pending&apos;,IMAGE(&quot;/resource/Pending&quot;, &quot;Pending&quot;,140,140),&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Planned_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Time__c</fullName>
    <label>Planned Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>PostPone</fullName>
                <isActive>false</isActive>
                <label>PostPone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/customNewExpenseController.cls
public class customNewExpenseController {

     public class dataBox{
        @AuraEnabled
        public Date Todaydate {get; set;}
        @AuraEnabled
        public Date yersterdaydate {get; set;}         
        @AuraEnabled
        public Date twodaydate {get; set;} 
        @AuraEnabled
        public string listId {get; set;} 
        @AuraEnabled
        public integer inprogressCount {get; set;}  
        @AuraEnabled
        public integer plannedCount {get; set;}   
     }
     @AuraEnabled
     public static dataBox getDates(){
             dataBox db = new dataBox();
             db.Todaydate = system.today();
             date mydate = system.today();
             db.twodaydate = mydate.addDays(-2);
             db.yersterdaydate = mydate.addDays(-1);
              List<ListView> listviews = [SELECT Id, Name FROM ListView WHERE SobjectType = 'Expense__c' and Name='All'];
			db.listId = listviews[0].Id;
             List<visit__c> inprogressList= [SELECT id,Name,Status__c FROM visit__c WHERE Status__c = 'In Progress' AND Planned_Start_Time__c = TODAY AND ownerId =:userinfo.getUserId()];
             db.inprogressCount = inprogressList.size();
              List<visit__c> plannedList= [SELECT id,Name,Status__c FROM visit__c WHERE Status__c = 'Planned' AND Planned_Start_Time__c = TODAY AND ownerId =:userinfo.getUserId()];
             db.plannedCount = plannedList.size();
             return db;
     }    
     @AuraEnabled
     public static Expense__c insertExpense(Expense__c expense){ 
        if(expense !=null ){
            upsert expense;
            return expense;
        }else{
            return null;
        }
        
    }
    @AuraEnabled
    public static void submitapproval(string expId){ 
        List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest>();
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setObjectId(expId);
        requests.add(req);
    	Approval.ProcessResult[] processResults = Approval.process(requests);
    
    
    }
    
}