force-app/main/default/objects/PO_Item__c/PO_Item__c.object-meta.xml
<CustomObject>
    <label>PO Item</label>
    <nameField>
        <displayFormat>POI-{0000}</displayFormat>
        <label>PO Items Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PO_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>PO Items</relationshipLabel>
    <relationshipName>PO_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PO_Item__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>PO Items</relationshipLabel>
    <relationshipName>PO_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Purchase  Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Purchase  Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/purchaseOrderControllerTest.cls
@isTest
public class purchaseOrderControllerTest {
    public static testmethod void testPO(){
         Warehouse__c wa = new Warehouse__c();
        wa.Name = 'test';
        insert wa;
        Warehouse__c wa1 = new Warehouse__c();
        wa1.Name = 'test';
        insert wa1;
		
		vendor__c acc = new vendor__c();
        acc.name = 'test';
        insert acc;
        
        Purchase_Order__c ord1 = new Purchase_Order__c();
        ord1.PO_Date__c =  system.today();
        ord1.Vendor__c = acc.id;
        insert ord1;   
        
        Product__c pr1 = new Product__c();
        pr1.MRP__c = 10;
        insert pr1;
        
        Product__c pr11 = new Product__c();
        pr11.MRP__c = 100;
        insert pr11;
            
        PO_Item__c odritem = new PO_Item__c();
        odritem.Product__c = pr1.id;
        odritem.Ordered_Quantity__c = 2;
        odritem.Unit_Price__c = 10;
        odritem.Purchase_Order__c = ord1.id;
        insert odritem;        
                PO_Item__c odritem1 = new PO_Item__c();
        odritem1.Product__c = pr11.id;
        odritem1.Ordered_Quantity__c = 100;
        odritem1.Unit_Price__c = 100;
        odritem1.Purchase_Order__c = ord1.id;
        insert odritem1;
                        PO_Item__c odritem11 = new PO_Item__c();
        odritem11.Product__c = pr11.id;
        odritem11.Ordered_Quantity__c = 25;
        odritem11.Unit_Price__c = 100;
        odritem11.Purchase_Order__c = ord1.id;
        insert odritem11;
        List<PO_Item__c> poList = new List<PO_Item__c>();
        PO_Item__c odritem12 = new PO_Item__c();
        odritem12.Product__c = pr11.id;
        odritem12.Ordered_Quantity__c = 25;
        odritem12.Unit_Price__c = 100;
        odritem12.Purchase_Order__c = ord1.id;
        poList.add(odritem12);
        test.startTest();
        purchaseOrderController.getdata(ord1.id);
        purchaseOrderController.getproductList();
        purchaseOrderController.getVendorList();
        purchaseOrderController.insertItemList(poList,ord1.id,'PO_Item__c',acc.Id,system.today());
        
    }

}