force-app/main/default/objects/PO_Item__c/PO_Item__c.object-meta.xml
<CustomObject>
    <label>PO Item</label>
    <nameField>
        <displayFormat>POI-{0000}</displayFormat>
        <label>PO Items Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PO_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>PO Items</relationshipLabel>
    <relationshipName>PO_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PO_Item__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>PO Items</relationshipLabel>
    <relationshipName>PO_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PO_Item__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/TAX_Per_GST__c.field-meta.xml
<CustomField>
    <fullName>TAX_Per_GST__c</fullName>
    <label>TAX Per(GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <label>Grand Total</label>
    <summarizedField>PO_Item__c.Total_inc_Tax__c</summarizedField>
    <summaryForeignKey>PO_Item__c.Purchase_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Purchase  Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Purchase  Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/purchaseOrderController.cls
public class purchaseOrderController {
     @AuraEnabled
    public static databox getdata(string recId){
        databox db = new databox();
        system.debug(recId);
        if(recId !=null && recId !=''){
        Purchase_order__c po = [SELECT Id,Name,Po_date__c,Vendor__c,vendor__r.Name,Grand_Total__c FROM Purchase_order__c WHERE Id=:recId];
        db.poDate = po.PO_Date__c;
        db.vendorId = po.Vendor__c;
        db.vendorName = po.vendor__r.Name;
        db.grandTotal = po.Grand_Total__c;
        db.recId = recId;
        db.recList = [SELECT Id, Name, Product__c, Ordered_Quantity__c, Unit_Price__c, Tax__c, Total_Price__c, Product_Name__c FROM PO_Item__c WHERE Purchase_order__c=:recId];    
        }
        db.productList = [SELECT Id,Name,Product_Code__c,TAX_Per_GST__c FROM Product__c];
        db.vendorList =  [SELECT Id,Name FROM Vendor__c];
        return db;
    }
    @AuraEnabled
    public static List<Product__c> getproductList(){    
        List<Product__c> listproducts =  [SELECT Id,Name,Product_Code__c FROM Product__c];
        return listproducts;
    }
    @AuraEnabled
    public static List<Vendor__c> getVendorList(){    
        List<Vendor__c> listvendors =  [SELECT Id,Name FROM Vendor__c];
        return listvendors;
    }
     @AuraEnabled
    public static string insertItemList(List<PO_Item__c> ItemList, string parentId, string objName, string vendorId, date poDate ){ 
        system.debug(ItemList + ' '+parentId);
        List<PO_Item__c> orList = new List<PO_Item__c>();
        Purchase_Order__c po = new Purchase_Order__c();
        po.Vendor__c = vendorId;
        po.PO_Date__c = poDate;
       insert po;
        for(PO_Item__c ol : ItemList){
            ol.Purchase_Order__c = po.id;
            orList.add(ol);
        }
        insert orList;
        return po.Id;
    }
     public class databox{
         @AuraEnabled
        public List<PO_Item__c> recList;
         @AuraEnabled
        public List<Product__c> productList;
         @AuraEnabled
        public List<Vendor__c> vendorList;
         @AuraEnabled
        public Decimal grandTotal;
          @AuraEnabled
        public string vendorId;
          @AuraEnabled
        public date poDate;
         @AuraEnabled
        public string vendorName;
        @AuraEnabled
        public string objectName;
         @AuraEnabled
        public string recId;
        
    }

}